version: '3.8'
services:
  springstudy:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
    command: ./mvnw spring-boot:run
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: spring_study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
